{
  imports = [
    ./alacritty.nix
    ./bat.nix
    ./chromium.nix
    ./eza.nix
    ./git.nix
    ./hyprland/default.nix
    ./lazygit.nix
    ./neovim.nix
    ./obsidian.nix
    ./ranger.nix
    ./starship.nix
    ./stylix.nix
    ./swaync/default.nix
    ./tmux.nix
    ./waybar/default.nix
    ./wofi/default.nix
    ./zathura.nix
    ./zsh.nix
  ];
}
